name: Get WandB Runs
on: [push]  

jobs:
  get-runs:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your repository under $GITHUB_WORKSPACE

      - name: Get Runs From Weights & Biases
        uses: machine-learning-apps/wandb-action@1.2  
        with:
          PROJECT_NAME: 'yinon-gold/mlops'  # Replace with your WandB entity and project names
          FILTER_GITHUB_SHA: ${{ github.sha }}  # Filters runs matching the commit SHA that triggered the action
          WANDB_API_KEY: 'bc09ba5761889f3ecfc86ca1ba79d002dc35b523'  # Your WandB API key
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # The GITHUB_TOKEN secret is automatically created by GitHub to use in your workflow
